@startuml C2_Container
!include <C4/C4_Container>

title C2 - Container Diagram - Picture Project Maintenance Tool

Person(user, "Photographer", "Uses the system to manage picture projects")

System_Boundary(system, "Picture Project Maintenance Tool") {
    Container(application, "Application", "C# / .NET", "Provides a CLI and website for project initialisation, image search, image selection, copying, metadata management and IrfanView interaction")
    ContainerDb(database, "Project Database", "Relational database", "Stores projects, images, metadata, subprojects, and selection sessions.")
}


System_Ext(fs, "File System", "Contains project folders, image files, project.info files and archive storage")
System_Ext(lightroom, "Adobe Lightroom", "Future integration for image editing workflow")
System_Ext(irfanview, "IrfanView", "External image viewer used to open open images and retrieve the currently opened image")

Rel(user, application, "Uses")

Rel(application, database, "Reads/writes", "SQL")
Rel(application, fs, "Reads/writes files and folders")
Rel_R(application, lightroom, "Prepares files for use in")
Rel(application, irfanview, "Opens images and retrieves current image")

@enduml